---
galaxy_info:
  author: Daniel Doherty
  description: Install pinned Neovim and bootstrap drd00's configuration
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
